apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
spec:
  containers:
    - name: jenkins-slave
      image: leifeng.harbor.com/jenkins/jnlp-slave:4.9-1-jdk11
      command:
        - sleep
      args:
        - 99d
