apiVersion: v1
kind: Pod
metadata:
  name: required-node-affinity
spec:
  containers:
    - name: required-node-affinity
      image: leifeng.harbor.com/library/myapp:v1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - node02
