apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-dm
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: env-container
          image: leifeng.harbor.com/library/myapp:v1
          env:
            - name: TEST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: TEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
