apiVersion: v1
kind: Pod
metadata:
  name: required-node-affinity
spec:
  containers:
    - name: required-node-affinity
      image: leifeng.harbor.com/library/myapp:v1
  tolerations:
    - key: name
      operator: Equal
      value: 123
      effect: NoSchedule
