apiVersion: v1
kind: Pod
metadata:
  name: required-pod-affinity
spec:
  containers:
    - name: myapp
      image: leifeng.harbor.com/library/myapp:v1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: kubernetes.io/hostname    
