apiVersion: v1
kind: Pod
metadata:
  name: producer-consumer
spec:
  containers:
  - name: producer 
    image: busybox
    args:
    - /bin/sh
    - -c
    - echo "hello kubernetes" > /producer_dir/hello; sleep 3000;
    volumeMounts:
    - name: shared-volume
      mountPath: /producer_dir
  - name: consumer
    image: busybox
    args:
    - /bin/sh
    - -c
    - cat /consumer_dir/hello; sleep 3000;
    volumeMounts:
    - name: shared-volume
      mountPath: /consumer_dir

  volumes:
  - name: shared-volume
    emptyDir: {}
