apiVersion: v1
kind: Pod
metadata:
  name: nfspod1
spec:
  containers:
  - name: nfspod1
    image: busybox
    args:
    - /bin/sh
    - -c
    - echo "hello kubernetes" > /mydata/hello; sleep 3000;
    volumeMounts:
    - mountPath: /mydata
      name: mydata

  volumes:
  - name: mydata
    nfs:
      path: /nfsdata
      server: 10.140.19.8

