apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-slave
  namespace: jenkins
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /workspace
    server: 192.168.2.240
