apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
    - name: nginx
      image: leifeng.harbor.com/library/nginx:v1
      volumeMounts:
        - name: host-volume
          mountPath: /data
  volumes:
    - name: host-volume
      hostPath:
        path: /data
        #type: Directory
