apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-pod
  namespace: default
spec:
  containers:
    - name: lifecycle-container
      image: leifeng.harbor.com/library/nginx:v1
      lifecycle:
        postStart:
          exec:
            command: ['/bin/sh', '-c', 'echo hello poststart > /var/log/message']
        preStop:
          exec:
            command: ['/bin/sh', '-c', 'echo hello prestop > /var/log/message'] 
